#!/usr/bin/env python3
"""
Unity Catalog Managed Table Test

This script tests creating a MANAGED table where:
1. Unity Catalog generates the storage location (in S3/MinIO)
2. Schema should be properly synced to UC metadata
3. Credentials are vended by UC server
"""

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
import sys


def create_spark_session():
    """Create SparkSession with Unity Catalog configuration."""
    return SparkSession.builder \
        .appName("UnityCatalog-ManagedTable-Test") \
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
        .config("spark.sql.catalog.unity", "io.unitycatalog.spark.UCSingleCatalog") \
        .config("spark.sql.catalog.unity.uri", "http://unity-catalog:8080") \
        .config("spark.sql.catalog.unity.token", "") \
        .config("spark.sql.defaultCatalog", "unity") \
        .config("spark.hadoop.fs.s3.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
        .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
        .config("spark.delta.logStore.s3a.impl", "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore") \
        .config("spark.hadoop.fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider") \
        .getOrCreate()


def main():
    print("=" * 70)
    print(" Unity Catalog MANAGED Table Test")
    print(" (Storage location generated by UC, stored in S3/MinIO)")
    print("=" * 70)

    spark = create_spark_session()
    spark.sparkContext.setLogLevel("WARN")
    print("\n[1/5] Spark session created")

    # Table configuration
    table_name = "managed_products"
    full_table_name = f"default.{table_name}"

    # Drop table if exists
    print(f"\n[2/5] Dropping table if exists: {full_table_name}")
    try:
        spark.sql(f"DROP TABLE IF EXISTS {full_table_name}")
        print("      Table dropped (if existed)")
    except Exception as e:
        print(f"      Note: {e}")

    # Create managed table with delta.feature.catalogManaged property
    print(f"\n[3/5] Creating MANAGED table: {full_table_name}")
    print("      Note: No LOCATION clause - UC will generate the S3 path")
    try:
        spark.sql(f"""
            CREATE TABLE {full_table_name} (
                product_id INT,
                product_name STRING,
                category STRING,
                price INT
            )
            USING DELTA
            TBLPROPERTIES ('delta.feature.catalogOwned-preview' = 'supported')
        """)
        print("      Managed table created successfully!")
    except Exception as e:
        print(f"      Error: {e}")
        spark.stop()
        return 1

    # Insert sample data
    print(f"\n[4/5] Inserting sample data...")
    try:
        spark.sql(f"""
            INSERT INTO {full_table_name} VALUES
            (1, 'Laptop', 'Electronics', 999),
            (2, 'Headphones', 'Electronics', 199),
            (3, 'Coffee Maker', 'Kitchen', 79),
            (4, 'Desk Chair', 'Furniture', 299),
            (5, 'Monitor', 'Electronics', 349)
        """)
        print("      Data inserted successfully!")
    except Exception as e:
        print(f"      Error: {e}")
        spark.stop()
        return 1

    # Verify data and show table info
    print(f"\n[5/5] Verifying table...")
    result = spark.sql(f"SELECT * FROM {full_table_name}")
    print(f"      Record count: {result.count()}")
    result.show(truncate=False)

    print("\n      Table details:")
    spark.sql(f"DESCRIBE TABLE EXTENDED {full_table_name}").show(truncate=False)

    # Summary
    print("\n" + "=" * 70)
    print(" Test Complete!")
    print("=" * 70)
    print(f" Table: {full_table_name}")
    print(" Type: MANAGED (location generated by UC)")
    print(" Check UC UI to verify columns are populated!")
    print("=" * 70)

    spark.stop()
    return 0


if __name__ == "__main__":
    sys.exit(main())